### ISSUE TITLE
get_file_size / blkgetsize opens block device more than once, fails with EBUSY on rumprun

### ISSUE THREAD

**Issue by mato** [mirage/mirage-block-unix#24]
While porting the block driver to run on rumprun, I've run into an issue with the way `get_file_size` and friends are implemented. On rumprun a block device is provided by rump_etfs and you cannot open it more than once. This causes `blkgetsize` to fail with `EBUSY`.

What needs to be done is the following:

1. `get_file_size` should be passed a file descriptor, not a file name.
2. calls to `stat()` should be replaced with `fstat()`.
3. `blkgetsize` needs to be modified to accept a file descriptor instead of a file name.
4. `blkgetsize` also needs the change at mato/mirage-block-unix-rumprun@c72afe9

Unfortunately, my OCaml-fu is not up to making these changes. Any help appreciated!

**Comment by djs55** [comment]
Let me know if this now works for you-- re-open if not!

**Comment by mato** [comment]
Works, thanks! I've opened #28 for the remaining trivial change needed to the blkgetsize stub.

**Comment by avsm** [comment]
should we cut a release as well @djs55? Would be nice if we had a way to track 'unreleased changesets' centrally

**Comment by djs55** [comment]
I'm happy to cut a release -- I was just waiting in case any other rump run
changes turned up. Shall I pull the trigger now?

On Wed, May 27, 2015 at 9:17 AM, Anil Madhavapeddy <notifications@github.com
> wrote:

> should we cut a release as well @djs55 <https://github.com/djs55>? Would
> be nice if we had a way to track 'unreleased changesets' centrally
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/mirage-block-unix/issues/24#issuecomment-105815611>
> .
>



-- 
Dave Scott

**Comment by mato** [comment]
I think I'm done with mirage-block from a rumprun point of view. However, I'm not depending on released versions of packages yet since I still need to sort out an issue with OASIS insisting on looking for DLL stub libraries despite those not getting built for rumprun.

**Comment by djs55** [comment]
OK, I'll cut a release now and we can always do another point release if some OASIS thing needs twiddling.

**Comment by djs55** [comment]
[ocaml/opam-repository#4145]
