### ISSUE TITLE
ERROR while installing mirage-block-unix.2.1.0

### ISSUE THREAD

**Issue by talex5** [mirage/mirage-block-unix#38]
Got this from Travis:

```
#=== ERROR while installing mirage-block-unix.2.1.0 ===========================#
# opam-version 1.2.2
# os           linux
# command      ocaml setup.ml -test
# path         /home/travis/.opam/system/build/mirage-block-unix.2.1.0
# compiler     system (4.02.3)
# exit-code    1
# env-file     /home/travis/.opam/system/build/mirage-block-unix.2.1.0/mirage-block-unix-36675-1114b2.env
# stdout-file  /home/travis/.opam/system/build/mirage-block-unix.2.1.0/mirage-block-unix-36675-1114b2.out
# stderr-file  /home/travis/.opam/system/build/mirage-block-unix.2.1.0/mirage-block-unix-36675-1114b2.err
### stdout ###
# [...]
# Raised at file "src/core/lwt.ml", line 789, characters 22-23
# Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
# Called from file "src/oUnit.ml", line 86, characters 13-17
# Called from file "src/oUnit.ml", line 97, characters 13-17
# Called from file "src/oUnitRunner.ml", line 46, characters 13-26
# 
# Failure("Block.read /tmp/mirage-block-test.37755.0 failed")
# ------------------------------------------------------------------------------
# Ran: 5 tests in: 0.23 seconds.
# FAILED: Cases: 5 Tried: 5 Errors: 1 Failures: 0 Skip:  0 Todo: 0 Timeouts: 0.
```

**Comment by talex5** [comment]
Problem goes away if compilig with `OPAMVERBOSE=y`. Maybe we should get opam to display enough context by default that you know which test failed?

**Comment by talex5** [comment]
The full error output:

    +cat mirage-block-unix-36683-1114b2.out
    .E...
    ==============================================================================
    Error: block:1:test open read.
    File "/home/travis/.opam/system/build/mirage-block-unix.2.1.0/_build/oUnit-block-testing-worker-linux-docker-1f642de6-3185-linux-1#00.log", line 23, characters 1-1:
    Error: block:1:test open read (in the log).
    Raised at file "src/core/lwt.ml", line 789, characters 22-23
    Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
    Called from file "src/oUnit.ml", line 86, characters 13-17
    Called from file "src/oUnit.ml", line 97, characters 13-17
    Called from file "src/oUnitRunner.ml", line 46, characters 13-26
    Failure("Block.read /tmp/mirage-block-test.37797.0 failed")
    ------------------------------------------------------------------------------
    Ran: 5 tests in: 0.05 seconds.
    FAILED: Cases: 5 Tried: 5 Errors: 1 Failures: 0 Skip:  0 Todo: 0 Timeouts: 0.

**Comment by talex5** [comment]
More verbose output (doesn't happen every time; just sometimes when building CueKeeper on Travis):

    # Failure("Block.read /tmp/mirage-block-test.38231.0 failed: read: Invalid argument in read '' at file /tmp/mirage-block-test.38231.0 offset 1048064 with length 512")

**Comment by djs55** [comment]
The `EINVAL` will probably go away with the switch to buffered by default...

**Comment by djs55** [comment]
I'll speculatively close this -- feel free to reopen upon more sightings.
